#!/bin/bash

i=1

while getopts ":n:" option;
do
  case $option in
    n)
      n=$OPTARG
      while [ $i -le 10 ]
      do
	  echo " $n x $i = $(( n * i ))"
            i=$(( i + 1 ))
      done
   esac
done
